Simulation = "nfinity"
Servers = 10
Rounds = 10
Hosts = 400
Bf = 299
Threshold = 201
GossipPeers = 9
Suite = "bn256.G2"
RunWait = "6000s"
Seed = 123456789
CommunicationMode = 1
Gossiptime = 150
MaxRoundLoops = 9999
Bandwidth = 50
Delay = 50

BlockSize
250000
500000
1000000
2000000