Simulation = "nfinity"
Servers = 10
Rounds = 10
Suite = "bn256.G2"
Seed = 123456789
RunWait = "6000s"
CommunicationMode = 1
Gossiptime = 150
BlockSize = 500000
MaxRoundLoops = 9999
Bandwidth = 50
Delay = 50

Hosts, Bf, Threshold, GossipPeers
10, 9, 6, 4
25, 24, 13, 5
50, 49, 26, 5
75, 74, 37, 7
100, 99, 51, 7