Simulation = "nfinity"
Servers = 1
Bf = 19
Rounds = 10
Suite = "bn256.G2"
Seed = 123456789
Threshold = 8
CommunicationMode = 1
Gossiptime = 100
GossipPeers = 2
BlockSize = 1000000
MaxRoundLoops = 4

Hosts
20